# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@tauri-apps/api-1.2.0" = {
      name = "_at_tauri-apps_slash_api";
      packageName = "@tauri-apps/api";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tauri-apps/api/-/api-1.2.0.tgz";
        sha512 = "lsI54KI6HGf7VImuf/T9pnoejfgkNoXveP14pVV7XarrQ46rOejIVJLFqHI9sRReJMGdh2YuCoI3cc/yCWCsrw==";
      };
    };
    "@types/ramda-0.28.23" = {
      name = "_at_types_slash_ramda";
      packageName = "@types/ramda";
      version = "0.28.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ramda/-/ramda-0.28.23.tgz";
        sha512 = "9TYWiwkew+mCMsL7jZ+kkzy6QXn8PL5/SKmBPmjgUlTpkokZWTBr+OhiIUDztpAEbslWyt24NNfEmZUBFmnXig==";
      };
    };
    "csstype-3.1.1" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.1.tgz";
        sha512 = "DJR/VvkAvSZW9bTouZue2sSxDwdTN92uHjqeKVm+0dAqdfNykRzQ95tay8aXMBAAPpUiq4Qcug2L7neoRh2Egw==";
      };
    };
    "ramda-0.28.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.28.0.tgz";
        sha512 = "9QnLuG/kPVgWvMQ4aODhsBUFKOUmnbUnsSXACv+NCQZcHbeb+v8Lodp8OVxtRULN1/xOyYLLaL6npE6dMq5QTA==";
      };
    };
    "solid-js-1.6.11" = {
      name = "solid-js";
      packageName = "solid-js";
      version = "1.6.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/solid-js/-/solid-js-1.6.11.tgz";
        sha512 = "JquQQHPArGq+i2PLURxJ99Pcz2/1docpbycSio/cKSA0SeI3z5zRjy0TNcH4NRYvbOLrcini+iovXwnexKabyw==";
      };
    };
    "ts-toolbelt-6.15.5" = {
      name = "ts-toolbelt";
      packageName = "ts-toolbelt";
      version = "6.15.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-toolbelt/-/ts-toolbelt-6.15.5.tgz";
        sha512 = "FZIXf1ksVyLcfr7M317jbB67XFJhOO1YqdTcuGaq9q5jLUoTikukZ+98TPjKiP2jC5CgmYdWWYs0s2nLSU0/1A==";
      };
    };
  };
  args = {
    name = "sidekick-dashboard";
    packageName = "sidekick-dashboard";
    version = "0.0.0";
    src = ./..;
    dependencies = [
      sources."@tauri-apps/api-1.2.0"
      sources."@types/ramda-0.28.23"
      sources."csstype-3.1.1"
      sources."ramda-0.28.0"
      sources."solid-js-1.6.11"
      sources."ts-toolbelt-6.15.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
